services:

  backend:

    build: .

    container_name: purplle_backend

    working_dir: /app/backend

    ports:
      - "8000:8000"

    command:
      - python
      - -m
      - uvicorn
      - app:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"

  dashboard:

    build: .

    container_name: purplle_dashboard

    working_dir: /app

    ports:
      - "8501:8501"

    command:
      - streamlit
      - run
      - dashboard/dashboard.py
      - --server.port=8501
      - --server.address=0.0.0.0

    depends_on:
      - backend

  replay:

    build: .

    container_name: purplle_replay

    working_dir: /app/backend

    command:
      - python
      - replay.py

    depends_on:
      - backend

